### ISSUE TITLE
升级到最新v0.0.36后vue2项目里完全不可使用

### ISSUE THREAD

**Issue by yuemeng200** [Simon-He95/fast-jump#2]
vscode版本: 1.85.2 (Universal)

**Comment by Simon-He95** [comment]
尝试升级到v0.0.37 看是否能解决

**Comment by yuemeng200** [comment]
还是不可用，刚才准备调试一下的，发现源码不开源了。。。

**Comment by Simon-He95** [comment]
我刚用vue2的项目调试了一下，最新版的应该是ok了～

> 还是不可用，刚才准备调试一下的，发现源码不开源了。。。
