### ISSUE TITLE
unplugin-vue-component 或者 unplugin-auto-import插件引起的问题

### ISSUE THREAD

**Issue by tata3358** [Simon-He95/fast-jump#4]
版本：v0.0.65
问题：
1. 如果项目使用了unplugin-vue-component 或者 unplugin-auto-import，跳转后components.d.ts或auto-imports.d文件无法打卡，跳转到的目标文件无法关闭
2. 卸载插件后，甚至是重装vscode，依旧有此问题。
![Screenity video - Jun 24, 2024](https://github.com/Simon-He95/fast-jump/assets/46048856/17f91b1c-bd8f-44e7-aab3-a9fe1ef871df)

**Comment by lyf3358** [comment]
![Uploading Screenity video - Jun 24, 2024.gif…]()

**Comment by Simon-He95** [comment]
这个auto-import的跳转不是这个插件处理的，你看看是否安装了下面的插件
<img width="597" alt="image" src="https://github.com/Simon-He95/fast-jump/assets/57086651/eaef2e59-9e35-48d2-8fee-78546af6f601">

**Comment by tata3358** [comment]
好的 大佬，检查了确实是你上面发的那个插件引起的，感谢
