### ISSUE TITLE
一些jump失效的地方

### ISSUE THREAD

**Issue by cbychen** [Simon-He95/fast-jump#5]
1.如果我的项目中设置了别名，引入方法时候 通过@/xxx/xxx方式引入，cmd+e 无法跳转
<img width="428" alt="image" src="https://github.com/user-attachments/assets/3fa915ca-9616-4190-b569-44cba6f2a789">

2.在vue2 项目中引入组件 注册组件时候 无法跳转到组件的文件中
<img width="461" alt="image" src="https://github.com/user-attachments/assets/dde3dabb-50ea-464b-87ed-c97d05a5d610">

3.在vue2 文件中引入一个constant常量定义的对象，也无法跳转（也是通过别名方式引入的）

**Comment by cbychen** [comment]
项目是用的webpack，别名是在 vue.config.js配的
<img width="209" alt="image" src="https://github.com/user-attachments/assets/d7c48ff0-617b-4181-ad13-ad56d0a27a6f">

**Comment by cbychen** [comment]
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@/*": ["src/*"],
			"@/components": ["src/components"]
		},
		"experimentalDecorators": true
	},
	"resolveExtensions": [".js", ".vue", ".ts"],
	"exclude": ["node_modules", "**/node_modules/*"]
}

**Comment by Lirous587** [comment]
> { "compilerOptions": { "baseUrl": ".", "paths": { "@/_": ["src/_"], "@/components": ["src/components"] }, "experimentalDecorators": true }, "resolveExtensions": [".js", ".vue", ".ts"], "exclude": ["node_modules", "**/node_modules/*"] }
解决方法是在你项目的根目录下新建一个jsconfig.json文件
然后设置相应的代替符号
这里我的项目使用 ` ~ ` 来代替的 `src` ，在 ` jsconfig.json ` 中也设置相应的代替符号就可以解决这个问题了

> vite.config.js的别名设置
```js
export default defineConfig({
  resolve: {
    alias: {
      "~": path.resolve(__dirname, "src"),
    },
  },
});
```

> jsconfig.json的别名解析
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": ["./src/**/*"]
}
```
